# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- testing
pr:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'stage1'
  pool: 
   name: manojbale
   demands:
   - Agent.Name -equals manojbale-agent2
  displayName: 'stage1'
  jobs:
  - deployment: stage1deploy
    timeoutInMinutes: 7200
    displayName: stage1deploy
    environment: 
     name: demo-dev
    strategy:
     runOnce:
       deploy:
         steps:
         - script: |
            echo test
           displayName: "test"
           continueOnError: true

- stage: 'stage2'
  displayName: 'stage2'
  jobs: 
  - deployment: stage2deploy
    timeoutInMinutes: 7200
    displayName: stage2deploy
    environment: 
     name: demo-uat
    strategy:
     runOnce:
       deploy:
         steps:
         - script: |
            echo test
           displayName: "test"
           continueOnError: true


  
