# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none


schedules:
#- cron: "*/15 * * * *"
#  displayName: Run for every 15 minutes
#  branches:
#    include:
#    - master
#  always: true

- cron: "06 15 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
    # - main
  always: true

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
