# #Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
  include:
  - develop/*
  - master
  

pr:
 autoCancel: false
 branches:
   include:
   - master
resources:
 repositories:
   - repository: self
     type: github
     name: dtlenv
     endpoint: manojbale
     ref: main

pool:
  vmImage: ubuntu-latest
steps:
- checkout: self
- script: |
   sleep 30
   echo hello




  
