name: BFF-HELM-DEPLOY-TEMPLATE

on:
 workflow_call:
   inputs:
    stage_name:
      required: true
      type: string
    cluster:
      required: true
      type: string
    resource_group:
      required: true
      type: string
    region:
      required: true
      type: string
    namespace:
      required: true
      type: string
    image_tag:
      required: true
      type: string
    subscription_id:
      required: true
      type: string
   secrets:
    AZURE_CREDENTIALS:
      required: true


jobs: 
 bff-helm-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Get the credentials 
        run: |
          echo "Testing the deployment"
          echo "az aks get-credentials --resource-group ${{ inputs.resource_group }} --name ${{ inputs.cluster }} --admin --overwrite-existing --subscription ${{ inputs.subscription_id }}"
          echo "az account set --subscription="f61bb119-e266-4de6-9db0-4c7a95a77d78"
          echo "${{ inputs.stage_name }} ${{ inputs.namespace }} ${{ inputs.image_tag }}"
  