# Terraform Workflow to deploy the BFF application in AKS clusters

name: BFF-HELM-DEPLOY

# Controls when the action will run. Manual trigger enabled.
on:
  workflow_dispatch:
   inputs:
    image_tag: 
     description: 'Provide specific version to deploy'
     type: string
     required: true
     default: latest
    region:
      description: 'Select the region'
      type: choice
      required: false
      options:
        - eus2
        - seasia
        - westeu
    environment:
      description: 'Select the environment'
      type: choice
      required: false
      options:
        - poc
        - dev
        - prod
    namespace:
      description: 'Select the AKS cluster namespace'
      type: choice
      required: false
      options:
        - test
        - int

jobs:
 poc-eus2-blue-test:
  if: ${{ inputs.environment == 'poc' }} && ${{ inputs.region == 'eus2' }} && ${{ inputs.namespace == 'test' }}
  uses: manojbale/JPetStore/.github/workflows/bff-helm-deploy-template.yml@master
  with:
    #variables used for setting up the helm template variables
    Cluster: poc
    Namespace: myfinance-test
    Region: eus2
    deployment_name: myfinance-bff
    environment_name: poc-eus2-blue-test
    resource_group: rg-poc-eastus2-blue
    cluster_name: aks-dscpoc-eus2-blue
    image_tag: latest
    subscription_id: f61bb119-e266-4de6-9db0-4c7a95a77d78
  secrets:
    AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    KUBE_CONFIG: /home/runner/.kube/config

 poc-eus2-blue-int:
   if: ${{ inputs.environment == 'poc' }} && ${{ inputs.region == 'eus2' }} && ${{ inputs.namespace == 'int' }}
   uses: manojbale/JPetStore/.github/workflows/bff-helm-deploy-template.yml@master
   with:
     #variables used for setting up the helm template variables
     Cluster: poc
     Namespace: myfinance-int
     Region: eus2
     deployment_name: myfinance-bff
     environment_name: poc-eus2-blue-int
     resource_group: rg-poc-eastus2-blue
     cluster_name: aks-dscpoc-eus2-blue
     image_tag: latest
     subscription_id: f61bb119-e266-4de6-9db0-4c7a95a77d78
   secrets:
     AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
     KUBE_CONFIG: /home/runner/.kube/config

 dev-eus2-blue-test:
  if: ${{ inputs.environment == 'dev' }} && ${{ inputs.region == 'eus2' }} && ${{ inputs.namespace == 'test' }}
  uses: manojbale/JPetStore/.github/workflows/bff-helm-deploy-template.yml@master
  with:
    #variables used for setting up the helm template variables
    Cluster: poc
    Namespace: myfinance-test
    Region: eus2
    deployment_name: myfinance-bff
    environment_name: poc-eus2-blue-test
    resource_group: rg-poc-eastus2-blue
    cluster_name: aks-dscpoc-eus2-blue
    image_tag: latest
    subscription_id: f61bb119-e266-4de6-9db0-4c7a95a77d78
  secrets:
    AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    KUBE_CONFIG: /home/runner/.kube/config

 dev-eus2-blue-int:
   if: ${{ inputs.environment == 'dev' }} && ${{ inputs.region == 'eus2' }} && ${{ inputs.namespace == 'int' }}
   uses: manojbale/JPetStore/.github/workflows/bff-helm-deploy-template.yml@master
   with:
     #variables used for setting up the helm template variables
     Cluster: poc
     Namespace: myfinance-int
     Region: eus2
     deployment_name: myfinance-bff
     environment_name: poc-eus2-blue-int
     resource_group: rg-poc-eastus2-blue
     cluster_name: aks-dscpoc-eus2-blue
     image_tag: latest
     subscription_id: f61bb119-e266-4de6-9db0-4c7a95a77d78
   secrets:
     AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
     KUBE_CONFIG: /home/runner/.kube/config