# Terraform Workflow to deploy the BFF application in AKS clusters

name: BFF-HELM-DEPLOY

# Controls when the action will run. Manual trigger enabled.
on:
  workflow_dispatch:
   inputs:
    image_tag: 
     description: 'Provide specific version to deploy'
     type: string
     required: true
     default: latest
    poc-eus2-blue-test:
     type: boolean
     description: 'deploy to poc-eus2-blue-test?'
     required: false
     default: false

    poc-eus2-blue-int:
     type: boolean
     description: 'deploy to poc-eus2-blue-int?'
     required: false
     default: false

    dev-eus2-blue-test:
     type: boolean
     description: 'deploy to dev-eus2-blue-test?'
     required: false
     default: false

    dev-eus2-blue-int:
     type: boolean
     description: 'deploy to dev-eus2-blue-int?'
     required: false
     default: false

jobs:
 poc-eus2-blue-test:
  if: ${{ inputs.poc-eus2-blue-test == true }}
  uses: cx-factory/cx-terraform-azure/.github/workflows/bff-helm-deploy-template.yml@feature/CXF1337-41
  with:
    #variables used for setting up the helm template variables
    Cluster: poc
    Namespace: myfinance-test
    Region: eus2
    deployment_name: myfinance-bff
    environment_name: poc-eus2-blue-test
    resource_group: rg-poc-eastus2-blue
    cluster_name: aks-dscpoc-eus2-blue
    image_tag: latest
    subscription_id: f61bb119-e266-4de6-9db0-4c7a95a77d78
  secrets:
    AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    KUBE_CONFIG: /home/runner/.kube/config

 poc-eus2-blue-int:
   if: ${{ inputs.poc-eus2-blue-int == true }}
   uses: cx-factory/cx-terraform-azure/.github/workflows/bff-helm-deploy-template.yml@feature/CXF1337-41
   with:
     #variables used for setting up the helm template variables
     Cluster: poc
     Namespace: myfinance-int
     Region: eus2
     deployment_name: myfinance-bff
     environment_name: poc-eus2-blue-int
     resource_group: rg-poc-eastus2-blue
     cluster_name: aks-dscpoc-eus2-blue
     image_tag: latest
     subscription_id: f61bb119-e266-4de6-9db0-4c7a95a77d78
   secrets:
     AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
     KUBE_CONFIG: /home/runner/.kube/config

 dev-eus2-blue-test:
  if: ${{ inputs.dev-eus2-blue-test == true }}
  uses: cx-factory/cx-terraform-azure/.github/workflows/bff-helm-deploy-template.yml@feature/CXF1337-41
  with:
    #variables used for setting up the helm template variables
    Cluster: poc
    Namespace: myfinance-test
    Region: eus2
    deployment_name: myfinance-bff
    environment_name: poc-eus2-blue-test
    resource_group: rg-poc-eastus2-blue
    cluster_name: aks-dscpoc-eus2-blue
    image_tag: latest
    subscription_id: f61bb119-e266-4de6-9db0-4c7a95a77d78
  secrets:
    AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    KUBE_CONFIG: /home/runner/.kube/config

 dev-eus2-blue-int:
   if: ${{ inputs.dev-eus2-blue-int == true }}
   uses: cx-factory/cx-terraform-azure/.github/workflows/bff-helm-deploy-template.yml@feature/CXF1337-41
   with:
     #variables used for setting up the helm template variables
     Cluster: poc
     Namespace: myfinance-int
     Region: eus2
     deployment_name: myfinance-bff
     environment_name: poc-eus2-blue-int
     resource_group: rg-poc-eastus2-blue
     cluster_name: aks-dscpoc-eus2-blue
     image_tag: latest
     subscription_id: f61bb119-e266-4de6-9db0-4c7a95a77d78
   secrets:
     AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
     KUBE_CONFIG: /home/runner/.kube/config